import re

REGEX_PATTERN_BOOK_NAME = r"^[A-Za-z0-9À-ž\s\.\,\-']+$"
REGEX_PATTERN_AUTHOR_NAME = r"^[A-Za-z0-9À-ž\s\.\,\-']+$"
REGEX_PATTERN_CITY = r"^[A-Za-z0-9À-ž\s\.\,\-']+$"

AUTHOR_NAME_RE = re.compile(REGEX_PATTERN_AUTHOR_NAME)
BOOK_NAME_RE = re.compile(REGEX_PATTERN_BOOK_NAME)
CITY_RE = re.compile(REGEX_PATTERN_CITY)

MAX_NAME_OR_AUTHOR_LENGTH = 64
MAX_CITY_LENGTH = 64
MAX_BOOK_TYPE_OR_STATUS_LENGTH = 20